// {
//     application_year: getCurrentAcademicYear(),
//     applied_for: 'Class V',
//     applicant_user: 'john.doe@example.com',
//     applied_to_ihs_before: 'No',
//     previous_application_application_year: '',
//     previous_application_applied_for: 'Class II',
//     previous_application_remarks: '',
//     first_name: 'John',
//     middle_name: '',
//     last_name: 'Doe',
//     gender: 'Male',
//     other_gender: '',
//     nationality: 'India',
//     country_of_residence: 'India',
//     country: 'India',
//     date_of_birth: '2012-01-01',
//     age: 12,
//     comm_address_country: 'India',
//     comm_address_area_code: '600001',
//     comm_address_line_1: '123 Main Street',
//     comm_address_line_2: 'Apt 4B',
//     comm_address_city: 'Chennai',
//     comm_address_state: 'Tamilnadu',
//     identification_mark_1: 'Mole on left cheek',
//     religion: 'Hindu',
//     community: 'OC',
//     identification_mark_2: 'Scar on right knee',
//     other_religion: '',
//     other_community: '',
//     mother_tongue: 'Tamil',
//     languages_known: [
//       { language: 'English', proficiency: 'Native' } // Default first language
//     ],
//     has_sibling_in_ihs: 'No',
//     // NEW Sibling fields
//     student_siblings: [], // Initialize as empty, will be populated if user selects 'Yes'
//     // END NEW Sibling fields
//     recent_photograph: undefined,
//     birth_certificate: undefined,
//     id_proof: 'Aadhaar Card',
//     id_proof_document: undefined,
//     aadhaar_number: '123456789012',
//     passport_number: '',
//     place_of_issue: '',
//     date_of_issue: '', // Initialize date strings
//     date_of_expiry: '', // Initialize date strings
//     is_home_schooled: 'No',
//     current_school_name: 'ABC Public School',
//     current_school_board_affiliation: 'CBSE',
//     current_school_phone_number: '9876543210',
//     current_school_country: 'India',
//     current_school_area_code: '600001',
//     current_school_city: 'Chennai',
//     current_school_state: 'Tamilnadu',
//     current_school_email_address: 'school@example.com',
//     current_school_a_line1: '456 School Road',
//     current_school_a_line2: '',
//     was_the_applicant_ever_home_schooled: 'No',
//     been_to_school_previously: 'Yes',
//     previous_schools: [], // Initialize as empty
//     emis_id: 'TN123456',
//     academic_strengths_and_weaknesses: 'Good in Math, needs improvement in English.',
//     hobbies_interests_and_extra_curricular_activities: 'Football, Painting',
//     other_details_of_importance: '',
//     temperament_and_personality: 'Calm and friendly',
//     special_learning_needs_or_learning_disability: 'None',
//     done_smallpox_vaccine: 'Yes',
//     done_hepatitis_a_vaccine: 'Yes',
//     done_hepatitis_b_vaccine: 'Yes',
//     done_tdap_vaccine: 'Yes',
//     done_typhoid_vaccine: 'Yes',
//     done_measles_vaccine: 'Yes',
//     done_polio_vaccine: 'Yes',
//     done_mumps_vaccine: 'Yes',
//     done_rubella_vaccine: 'Yes',
//     done_varicella_vaccine: 'Yes',
//     other_vaccines: '',
//     vaccine_certificates: undefined,
//     blood_group: 'Blood Group O+',
//     wears_glasses_or_lens: 'No',
//     right_eye_power: '',
//     left_eye_power: '',
//     is_toilet_trained: 'Yes',
//     wets_bed: 'No',
//     bed_wet_frequency: '',
//     has_hearing_challenges: 'No',
//     hearing_challenges: '',
//     has_behavioural_challenges: 'No',
//     behavioural_challenges: '',
//     has_physical_challenges: 'No',
//     physical_challenges: '',
//     has_speech_challenges: 'No',
//     speech_challenges: '',
//     has_injury: 'No',
//     injury_details: '',
//     on_medication: 'No',
//     medication_details: '',
//     medical_prescription: undefined,
//     has_health_issue: 'No',
//     health_issue_details: '',
//     was_hospitalized: 'No',
//     hospitalization_details: '',
//     needs_special_attention: 'No',
//     attention_details: '',
//     has_allergies: 'No', // Fixed typo
//     // NEW Parent fields
//     students_parents: [ // Initialize with one parent (e.g., Father)
//       {
//         parent_first_name: 'Richard',
//         parent_last_name: 'Roe',
//         parent_relation: 'Father',
//         parent_nationality: 'India',
//         parent_country_of_residence: 'India',
//         parent_contact_email: 'richard.roe@example.com',
//         parent_contact_phone: '+919876543210',
//         parent_is_whatsapp_same: true as boolean,
//         parent_whatsapp_number: '',
//         parent_is_address_same_as_applicant: 'Yes', // Default to Yes
//         parent_address_country: '', // Will be copied or filled if No
//         parent_address_zipcode: '',
//         parent_address_state: '',
//         parent_address_city: '',
//         parent_address_line1: '',
//         parent_address_line2: '',
//         parent_education: 'Graduate', // Example default
//         parent_field_of_study: 'Engineering',
//         parent_profession: 'Businessman/ Entrepreneur', // Example default
//         parent_organization_name: 'Roe Corp',
//         parent_designation: 'CEO',
//         parent_annual_income: '5000000',
//       }],
//     // END NEW Parent fields
//     parent_marital_status: 'Married',
//     who_is_responsible_for_paying_applicants_tuition_fee: undefined, // Fixed typo
//     court_order_document: undefined,
//     who_is_allowed_to_receive_school_communication: undefined,
//     legal_rights_document: undefined,
//     who_is_allowed_to_receive_report_cards: undefined,
//     visit_rights: undefined,
//     parents_are_local_guardians: 'Yes', // Default to Yes, so guardian section is hidden
//     student_guardians: [],
//     group_a: undefined,
//     group_c: undefined,
//     group_b: undefined,
//     group_d: undefined,
//     q1_applicant_response: '',
//     q2_applicant_response: '',
//     q3_applicant_response: '',
//     q4_applicant_response: '',
//     q5_applicant_response: '',
//     q6_applicant_response: '',
//     q7_applicant_response: '',
//     q1_parent_response: '',
//     q2_parent_response: '',
//     q3_parent_response: '',
//     q4_parent_response: '',
//     q5_parent_response: '',
//     q6_parent_response: '',
//     tnc_check: false,
//     date: '2024-06-01', // Initialize date strings
//     place: 'Chennai',
//     billing_name: 'John Doe',
//     billing_phone: '+919876543210',
//     billing_email: 'john.doe@example.com',
//     billing_country: 'India',
//     billing_area_code: '600001',
//     billing_city: 'Chennai',
//     billing_state: 'Tamilnadu',
//     billing_address_l1: '123 Main Street',
//     billing_address_l2: '',
//     application_fee_status: 'Pending',
//     program: 'General',
//     payment_program_links: [], // Keep if still table
//     amended_from: '',
//     application_feedback_status: 'Yes', // Changed from 'Pending' to a valid option
//     application_feedback: '',
//     orientation_feedback_status: 'Yes', // Changed from 'Pending' to a valid option
//     academics_feedback: '',
//     group_activities_feedback: '',
//     sports_feedback: '',
//     dining: '',
//     other_feedback: '',
//     interview_feedback_status: 'Probable Yes', // Changed from 'Pending' to a valid option
//     interview_feedback: '',
//   }